data_params:
  path_result: ./data/318.result
  path_test: ./data/318.test
  path_train: ./data/318.train
  sep: table
  voc_params:
    char: {min_count: 0, path: ./Res/voc/char.voc.pkl}
    f1: {min_count: 0, path: ./Res/voc/f1.voc.pkl}
    f2: {min_count: 0, path: ./Res/voc/f2.voc.pkl}
    f3: {min_count: 0, path: ./Res/voc/f3.voc.pkl}
    label: {min_count: 0, path: ./Res/voc/label.voc.pkl}
model: NER
model_params:
  batch_size: 64
  bilstm_params: {num_layers: 1, num_units: 256, rnn_dropout: 0.2}
  clip: 10
  conv_dropout: 0.2
  conv_filter_len_list: [1, 2, 3, 4, 5]
  conv_filter_size_list: [8, 8, 8, 8, 8]
  dev_size: 0.1
  dropout_rate: 0.3
  embed_params:
    char:
      dropout_rate: 0.3
      path: null
      path_pre_train: null
      shape: [85, 16]
    f1:
      dropout_rate: 0.3
      path: null
      path_pre_train: null
      shape: [2689, 64]
    f2:
      dropout_rate: 0.4
      path: null
      path_pre_train: null
      shape: [53, 32]
    f3:
      dropout_rate: 0.3
      path: null
      path_pre_train: null
      shape: [15, 32]
  feature_names: [f1, f2, f3]
  l2_rate: 0.001
  learning_rate: 0.002
  max_patience: 5
  nb_classes: 57
  nb_epoch: 200
  path_model: ./Model/best_model_intent
  rnn_unit: gru
  sequence_len_pt: 99
  sequence_length: 21
  use_char_feature: false
  use_crf: true
  word_len_pt: 95
  word_length: 11
